spring.application.name=Backend_SportCourtBooking

spring.datasource.url=jdbc:mysql://localhost:3306/sport_booking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=heorom123


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=7200000
application.security.otp.expiration-minutes=5


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nghiatrinh3035@gmail.com
spring.mail.password=zptyxjsddkybwekw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL của ngrok (Bạn sẽ thay đổi URL này mỗi khi bật ngrok lại nếu dùng bản free)
app.base-url=https://patchwork-florist-lyrics.ngrok-free.dev

payment.vnpay.tmn-code=39GC517I
payment.vnpay.secret-key=GFXZA869IZ7RFDI14ET9ZVNB882369OM
payment.vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnpay.return-url=${app.base-url}/api/payments/vnpay-return

# Google OAuth2 Configuration (Thay thế bằng Client ID từ Google Cloud Console)
google.client-id=157152900877-0qhf23cdnqaclo066s9eddja26o5bef3.apps.googleusercontent.com

server.port=8080